apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice3-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice3-user-service
  template:
    metadata:
      labels:
        app: microservice3-user-service
    spec:
      containers:
        - name: microservice3-user-service
          image: microservice3-user-service:local
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://aikanshboyal:aikanshiscool@cluster0.yicdivk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice3-user-service
spec:
  selector:
    app: microservice3-user-service
  ports:
    - port: 80
      targetPort: 3000
  type: NodePort
